version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

mkdocs:
  configuration: mkdocs.yaml
  fail_on_warning: false

formats: all

python:
  install:
    - requirements: requirements.txt
