site_name: Tobas
theme: readthedocs # cf. https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes
nav:
  - Introduction: index.md # Required
  - Getting Started:
      - Installation: getting_started/installation.md
      - Boot Device Configuration: getting_started/bootmedia_config.md
      - Setup Assistant: getting_started/setup_assistant.md
      - Hardware Setup: getting_started/hardware_setup.md
      - Flight Test: getting_started/flight_test.md
      - Simulation: getting_started/simulation.md
  - For Developers:
      - ROS API: for_developers/ros_api.md
      - User Code (Python): for_developers/user_code_py.md
      - User Code (C++): for_developers/user_code_cpp.md
  - Additional Information:
      - What is UADF: additional_information/what_is_uadf.md
      - Inertia Moment: additional_information/inertia_moment.md
      - 3D Models: additional_information/cad_models.md
      - System Architecture: additional_information/system_architecture.md
      - Trouble Shooting: additional_information/trouble_shooting.md
  - Release:
      - Releases: releases/releases.md
      - Process: releases/process.md
markdown_extensions:
  - admonition # Required for "note"
  - pymdownx.arithmatex: # Required for writing equations
      generic: true
  - toc:
      permalink: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
